apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: anudhauthsala/sit323-2025-prac5p:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production